// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismic from "@prismicio/client";

type Simplify<T> = { [KeyType in keyof T]: T[KeyType] };

/**
 * Item in *About → Intro Images*
 */
export interface AboutDocumentDataIntroImagesItem {
  /**
   * Image field in *About → Intro Images*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: about.intro_images[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;
}

/**
 * Item in *About → Experience*
 */
export interface AboutDocumentDataExperienceItem {
  /**
   * Time field in *About → Experience*
   *
   * - **Field Type**: Text
   * - **Placeholder**: Ongoing / Year (eg 2024)
   * - **API ID Path**: about.experience[].time
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  time: prismic.KeyTextField;

  /**
   * Company field in *About → Experience*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: about.experience[].company
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  company: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * Description field in *About → Experience*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: about.experience[].description
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  description: prismic.KeyTextField;
}

/**
 * Item in *About → Currently Reading*
 */
export interface AboutDocumentDataCurrentlyReadingItem {
  /**
   * Image field in *About → Currently Reading*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: about.currently_reading[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * Name field in *About → Currently Reading*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: about.currently_reading[].name
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  name: prismic.KeyTextField;

  /**
   * Author field in *About → Currently Reading*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: about.currently_reading[].author
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  author: prismic.KeyTextField;
}

/**
 * Item in *About → Things I like*
 */
export interface AboutDocumentDataThingsLikeItem {
  /**
   * Label field in *About → Things I like*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: about.things_like[].label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  label: prismic.KeyTextField;

  /**
   * Link field in *About → Things I like*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: about.things_like[].link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;
}

/**
 * Item in *About → Things I Don't Like*
 */
export interface AboutDocumentDataThingsNotLikeItem {
  /**
   * Label field in *About → Things I Don't Like*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: about.things_not_like[].label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  label: prismic.KeyTextField;

  /**
   * Link field in *About → Things I Don't Like*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: about.things_not_like[].link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;
}

/**
 * Item in *About → Bucket List*
 */
export interface AboutDocumentDataBucketListItem {
  /**
   * Text field in *About → Bucket List*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: about.bucket_list[].text
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  text: prismic.KeyTextField;

  /**
   * Done field in *About → Bucket List*
   *
   * - **Field Type**: Boolean
   * - **Placeholder**: *None*
   * - **Default Value**: false
   * - **API ID Path**: about.bucket_list[].done
   * - **Documentation**: https://prismic.io/docs/field#boolean
   */
  done: prismic.BooleanField;
}

type AboutDocumentDataSlicesSlice = never;

/**
 * Content for About documents
 */
interface AboutDocumentData {
  /**
   * Intro Images field in *About*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: about.intro_images[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  intro_images: prismic.GroupField<Simplify<AboutDocumentDataIntroImagesItem>>;

  /**
   * Description field in *About*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: about.description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  description: prismic.KeyTextField;

  /**
   * Experience field in *About*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: about.experience[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  experience: prismic.GroupField<Simplify<AboutDocumentDataExperienceItem>>;

  /**
   * Currently Reading field in *About*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: about.currently_reading[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  currently_reading: prismic.GroupField<
    Simplify<AboutDocumentDataCurrentlyReadingItem>
  >;

  /**
   * Things I like field in *About*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: about.things_like[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  things_like: prismic.GroupField<Simplify<AboutDocumentDataThingsLikeItem>>;

  /**
   * Things I Don't Like field in *About*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: about.things_not_like[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  things_not_like: prismic.GroupField<
    Simplify<AboutDocumentDataThingsNotLikeItem>
  >;

  /**
   * Bucket List field in *About*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: about.bucket_list[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  bucket_list: prismic.GroupField<Simplify<AboutDocumentDataBucketListItem>>;

  /**
   * Slice Zone field in *About*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: about.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<AboutDocumentDataSlicesSlice>;
}

/**
 * About document from Prismic
 *
 * - **API ID**: `about`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type AboutDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<Simplify<AboutDocumentData>, "about", Lang>;

/**
 * Item in *Colophon → Typography*
 */
export interface ColophonDocumentDataTypographyItem {
  /**
   * Image field in *Colophon → Typography*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: colophon.typography[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;

  /**
   * Description field in *Colophon → Typography*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: colophon.typography[].description
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  description: prismic.KeyTextField;
}

/**
 * Item in *Colophon → Inspiration Links*
 */
export interface ColophonDocumentDataInspirationLinksItem {
  /**
   * Link field in *Colophon → Inspiration Links*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: colophon.inspiration_links[].link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;
}

/**
 * Item in *Colophon → Good People*
 */
export interface ColophonDocumentDataGoodPeopleItem {
  /**
   * Link field in *Colophon → Good People*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: colophon.good_people[].link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;
}

type ColophonDocumentDataSlicesSlice = never;

/**
 * Content for Colophon documents
 */
interface ColophonDocumentData {
  /**
   * Typography field in *Colophon*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: colophon.typography[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  typography: prismic.GroupField<Simplify<ColophonDocumentDataTypographyItem>>;

  /**
   * Photography Description field in *Colophon*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: colophon.photography
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  photography: prismic.KeyTextField;

  /**
   * Inspiration Description field in *Colophon*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: colophon.inspiration_description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  inspiration_description: prismic.KeyTextField;

  /**
   * Inspiration Links field in *Colophon*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: colophon.inspiration_links[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  inspiration_links: prismic.GroupField<
    Simplify<ColophonDocumentDataInspirationLinksItem>
  >;

  /**
   * Good People Description field in *Colophon*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: colophon.good_people_description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  good_people_description: prismic.KeyTextField;

  /**
   * Good People field in *Colophon*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: colophon.good_people[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  good_people: prismic.GroupField<Simplify<ColophonDocumentDataGoodPeopleItem>>;

  /**
   * Slice Zone field in *Colophon*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: colophon.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<ColophonDocumentDataSlicesSlice> /**
   * Meta Title field in *Colophon*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: colophon.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Colophon*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: colophon.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Colophon*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: colophon.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Colophon document from Prismic
 *
 * - **API ID**: `colophon`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type ColophonDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<ColophonDocumentData>,
    "colophon",
    Lang
  >;

/**
 * Item in *Homepage → Links*
 */
export interface HomepageDocumentDataLinksItem {
  /**
   * Label field in *Homepage → Links*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.links[].label
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  label: prismic.KeyTextField;

  /**
   * Link field in *Homepage → Links*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.links[].link
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  link: prismic.LinkField<string, string, unknown, prismic.FieldState, never>;
}

type HomepageDocumentDataSlicesSlice = never;

/**
 * Content for Homepage documents
 */
interface HomepageDocumentData {
  /**
   * Main Text field in *Homepage*
   *
   * - **Field Type**: Rich Text
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.main_text
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#rich-text-title
   */
  main_text: prismic.RichTextField;

  /**
   * Links field in *Homepage*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.links[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  links: prismic.GroupField<Simplify<HomepageDocumentDataLinksItem>>;

  /**
   * Slice Zone field in *Homepage*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<HomepageDocumentDataSlicesSlice> /**
   * Meta Title field in *Homepage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: homepage.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Homepage*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: homepage.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Homepage*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: homepage.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Homepage document from Prismic
 *
 * - **API ID**: `homepage`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomepageDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<HomepageDocumentData>,
    "homepage",
    Lang
  >;

type VisualDocumentDataSlicesSlice = VisualImageRowSlice;

/**
 * Content for Visuals documents
 */
interface VisualDocumentData {
  /**
   * Slice Zone field in *Visuals*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: visual.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<VisualDocumentDataSlicesSlice> /**
   * Meta Title field in *Visuals*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A title of the page used for social media and search engines
   * - **API ID Path**: visual.meta_title
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */;
  meta_title: prismic.KeyTextField;

  /**
   * Meta Description field in *Visuals*
   *
   * - **Field Type**: Text
   * - **Placeholder**: A brief summary of the page
   * - **API ID Path**: visual.meta_description
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  meta_description: prismic.KeyTextField;

  /**
   * Meta Image field in *Visuals*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: visual.meta_image
   * - **Tab**: SEO & Metadata
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  meta_image: prismic.ImageField<never>;
}

/**
 * Visuals document from Prismic
 *
 * - **API ID**: `visual`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type VisualDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithoutUID<
    Simplify<VisualDocumentData>,
    "visual",
    Lang
  >;

/**
 * Item in *Work → People Worked With*
 */
export interface WorkDocumentDataPeopleWorkedItem {
  /**
   * Name field in *Work → People Worked With*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: work.people_worked[].name
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  name: prismic.KeyTextField;

  /**
   * Link field in *Work → People Worked With*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: work.people_worked[].link
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  link: prismic.KeyTextField;
}

/**
 * Item in *Work → Services*
 */
export interface WorkDocumentDataServicesItem {
  /**
   * service field in *Work → Services*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: work.services[].service
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  service: prismic.KeyTextField;
}

type WorkDocumentDataSlicesSlice = never;

type WorkDocumentDataSlices1Slice = WorkContentSlice;

/**
 * Content for Work documents
 */
interface WorkDocumentData {
  /**
   * Main Image field in *Work*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: work.main_image
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  main_image: prismic.ImageField<never>;

  /**
   * Name field in *Work*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: work.name
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  name: prismic.KeyTextField;

  /**
   * Description field in *Work*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: work.description
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  description: prismic.KeyTextField;

  /**
   * Project Link field in *Work*
   *
   * - **Field Type**: Link
   * - **Placeholder**: *None*
   * - **API ID Path**: work.project_link
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#link-content-relationship
   */
  project_link: prismic.LinkField<
    string,
    string,
    unknown,
    prismic.FieldState,
    never
  >;

  /**
   * People Worked With field in *Work*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: work.people_worked[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  people_worked: prismic.GroupField<Simplify<WorkDocumentDataPeopleWorkedItem>>;

  /**
   * Release Date field in *Work*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: work.release_date
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  release_date: prismic.KeyTextField;

  /**
   * Services field in *Work*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: work.services[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  services: prismic.GroupField<Simplify<WorkDocumentDataServicesItem>>;

  /**
   * Slice Zone field in *Work*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: work.slices[]
   * - **Tab**: Main
   * - **Documentation**: https://prismic.io/docs/field#slices
   */
  slices: prismic.SliceZone<WorkDocumentDataSlicesSlice> /**
   * Slice Zone field in *Work*
   *
   * - **Field Type**: Slice Zone
   * - **Placeholder**: *None*
   * - **API ID Path**: work.slices1[]
   * - **Tab**: Content
   * - **Documentation**: https://prismic.io/docs/field#slices
   */;
  slices1: prismic.SliceZone<WorkDocumentDataSlices1Slice>;
}

/**
 * Work document from Prismic
 *
 * - **API ID**: `work`
 * - **Repeatable**: `true`
 * - **Documentation**: https://prismic.io/docs/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type WorkDocument<Lang extends string = string> =
  prismic.PrismicDocumentWithUID<Simplify<WorkDocumentData>, "work", Lang>;

export type AllDocumentTypes =
  | AboutDocument
  | ColophonDocument
  | HomepageDocument
  | VisualDocument
  | WorkDocument;

/**
 * Item in *VisualMediaRow → Default → Primary → Media*
 */
export interface VisualImageRowSliceDefaultPrimaryMediaItem {
  /**
   * Media field in *VisualMediaRow → Default → Primary → Media*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: visual_image_row.default.primary.media[].media
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  media: prismic.ImageField<never>;

  /**
   * Variant field in *VisualMediaRow → Default → Primary → Media*
   *
   * - **Field Type**: Select
   * - **Placeholder**: *None*
   * - **API ID Path**: visual_image_row.default.primary.media[].variant
   * - **Documentation**: https://prismic.io/docs/field#select
   */
  variant: prismic.SelectField<"Portrait" | "Landscape">;
}

/**
 * Primary content in *VisualMediaRow → Default → Primary*
 */
export interface VisualImageRowSliceDefaultPrimary {
  /**
   * Media field in *VisualMediaRow → Default → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: visual_image_row.default.primary.media[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  media: prismic.GroupField<
    Simplify<VisualImageRowSliceDefaultPrimaryMediaItem>
  >;
}

/**
 * Default variation for VisualMediaRow Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type VisualImageRowSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<VisualImageRowSliceDefaultPrimary>,
  never
>;

/**
 * Slice variation for *VisualMediaRow*
 */
type VisualImageRowSliceVariation = VisualImageRowSliceDefault;

/**
 * VisualMediaRow Shared Slice
 *
 * - **API ID**: `visual_image_row`
 * - **Description**: VisualImageRow
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type VisualImageRowSlice = prismic.SharedSlice<
  "visual_image_row",
  VisualImageRowSliceVariation
>;

/**
 * Item in *WorkContent → Image Row → Primary → Image Row (Max 2 Images)*
 */
export interface WorkContentSliceImageRowPrimaryImageRowItem {
  /**
   * Image field in *WorkContent → Image Row → Primary → Image Row (Max 2 Images)*
   *
   * - **Field Type**: Image
   * - **Placeholder**: *None*
   * - **API ID Path**: work_content.imageRow.primary.image_row[].image
   * - **Documentation**: https://prismic.io/docs/field#image
   */
  image: prismic.ImageField<never>;
}

/**
 * Primary content in *WorkContent → Default → Primary*
 */
export interface WorkContentSliceDefaultPrimary {
  /**
   * Description field in *WorkContent → Default → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: work_content.default.primary.description
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  description: prismic.KeyTextField;
}

/**
 * Default variation for WorkContent Slice
 *
 * - **API ID**: `default`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type WorkContentSliceDefault = prismic.SharedSliceVariation<
  "default",
  Simplify<WorkContentSliceDefaultPrimary>,
  never
>;

/**
 * Primary content in *WorkContent → Image Row → Primary*
 */
export interface WorkContentSliceImageRowPrimary {
  /**
   * Image Row (Max 2 Images) field in *WorkContent → Image Row → Primary*
   *
   * - **Field Type**: Group
   * - **Placeholder**: *None*
   * - **API ID Path**: work_content.imageRow.primary.image_row[]
   * - **Documentation**: https://prismic.io/docs/field#group
   */
  image_row: prismic.GroupField<
    Simplify<WorkContentSliceImageRowPrimaryImageRowItem>
  >;
}

/**
 * Image Row variation for WorkContent Slice
 *
 * - **API ID**: `imageRow`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type WorkContentSliceImageRow = prismic.SharedSliceVariation<
  "imageRow",
  Simplify<WorkContentSliceImageRowPrimary>,
  never
>;

/**
 * Primary content in *WorkContent → Text With Header → Primary*
 */
export interface WorkContentSliceTextWithHeaderPrimary {
  /**
   * Header field in *WorkContent → Text With Header → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: work_content.textWithHeader.primary.header
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  header: prismic.KeyTextField;

  /**
   * Description field in *WorkContent → Text With Header → Primary*
   *
   * - **Field Type**: Text
   * - **Placeholder**: *None*
   * - **API ID Path**: work_content.textWithHeader.primary.description
   * - **Documentation**: https://prismic.io/docs/field#key-text
   */
  description: prismic.KeyTextField;
}

/**
 * Text With Header variation for WorkContent Slice
 *
 * - **API ID**: `textWithHeader`
 * - **Description**: Default
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type WorkContentSliceTextWithHeader = prismic.SharedSliceVariation<
  "textWithHeader",
  Simplify<WorkContentSliceTextWithHeaderPrimary>,
  never
>;

/**
 * Slice variation for *WorkContent*
 */
type WorkContentSliceVariation =
  | WorkContentSliceDefault
  | WorkContentSliceImageRow
  | WorkContentSliceTextWithHeader;

/**
 * WorkContent Shared Slice
 *
 * - **API ID**: `work_content`
 * - **Description**: WorkContent
 * - **Documentation**: https://prismic.io/docs/slice
 */
export type WorkContentSlice = prismic.SharedSlice<
  "work_content",
  WorkContentSliceVariation
>;

declare module "@prismicio/client" {
  interface CreateClient {
    (
      repositoryNameOrEndpoint: string,
      options?: prismic.ClientConfig,
    ): prismic.Client<AllDocumentTypes>;
  }

  interface CreateWriteClient {
    (
      repositoryNameOrEndpoint: string,
      options: prismic.WriteClientConfig,
    ): prismic.WriteClient<AllDocumentTypes>;
  }

  interface CreateMigration {
    (): prismic.Migration<AllDocumentTypes>;
  }

  namespace Content {
    export type {
      AboutDocument,
      AboutDocumentData,
      AboutDocumentDataIntroImagesItem,
      AboutDocumentDataExperienceItem,
      AboutDocumentDataCurrentlyReadingItem,
      AboutDocumentDataThingsLikeItem,
      AboutDocumentDataThingsNotLikeItem,
      AboutDocumentDataBucketListItem,
      AboutDocumentDataSlicesSlice,
      ColophonDocument,
      ColophonDocumentData,
      ColophonDocumentDataTypographyItem,
      ColophonDocumentDataInspirationLinksItem,
      ColophonDocumentDataGoodPeopleItem,
      ColophonDocumentDataSlicesSlice,
      HomepageDocument,
      HomepageDocumentData,
      HomepageDocumentDataLinksItem,
      HomepageDocumentDataSlicesSlice,
      VisualDocument,
      VisualDocumentData,
      VisualDocumentDataSlicesSlice,
      WorkDocument,
      WorkDocumentData,
      WorkDocumentDataPeopleWorkedItem,
      WorkDocumentDataServicesItem,
      WorkDocumentDataSlicesSlice,
      WorkDocumentDataSlices1Slice,
      AllDocumentTypes,
      VisualImageRowSlice,
      VisualImageRowSliceDefaultPrimaryMediaItem,
      VisualImageRowSliceDefaultPrimary,
      VisualImageRowSliceVariation,
      VisualImageRowSliceDefault,
      WorkContentSlice,
      WorkContentSliceDefaultPrimary,
      WorkContentSliceImageRowPrimaryImageRowItem,
      WorkContentSliceImageRowPrimary,
      WorkContentSliceTextWithHeaderPrimary,
      WorkContentSliceVariation,
      WorkContentSliceDefault,
      WorkContentSliceImageRow,
      WorkContentSliceTextWithHeader,
    };
  }
}
