// Code generated by Slice Machine. DO NOT EDIT.

import { defineAsyncComponent } from "vue";
import { defineSliceZoneComponents } from "@prismicio/vue";

export const components = defineSliceZoneComponents({
  catalog_item: defineAsyncComponent(() => import("./CatalogItem/index.vue")),
  visual_image_row: defineAsyncComponent(
    () => import("./VisualMediaRow/index.vue"),
  ),
  work_content: defineAsyncComponent(() => import("./WorkContent/index.vue")),
});
